// ─── ARCANA SVGs ───
const ARCANA_SVG = {
  "0": `<svg viewBox="0 0 44 44" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><circle cx="22" cy="10" r="4"/><path d="M22 14v14"/><path d="M14 20l8 4 8-4"/><path d="M18 36l4-8 4 8"/><path d="M8 30c4-2 8 2 14-2s10 0 14-2"/></svg>`,
  "1": `<svg viewBox="0 0 44 44" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"><path d="M22 6v6"/><path d="M12 16h20"/><path d="M16 16c0 8 2 14 6 16s6-8 6-16"/><circle cx="22" cy="38" r="2"/></svg>`,
  "2": `<svg viewBox="0 0 44 44" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"><path d="M14 8h16v20a8 8 0 01-16 0V8z"/><path d="M14 18h16"/><path d="M14 24h10"/><circle cx="22" cy="10" r="2"/></svg>`,
  "3": `<svg viewBox="0 0 44 44" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"><circle cx="22" cy="16" r="8"/><path d="M10 36c0-8 5-12 12-12s12 4 12 12"/><path d="M18 10c-2-4 6-4 8 0"/></svg>`,
  "4": `<svg viewBox="0 0 44 44" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><rect x="12" y="10" width="20" height="24" rx="2"/><path d="M16 10V8h12v2"/><path d="M16 22h12"/><path d="M16 26h8"/></svg>`,
  "5": `<svg viewBox="0 0 44 44" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"><path d="M22 6l2 6h6l-5 4 2 6-5-4-5 4 2-6-5-4h6z"/><path d="M14 28v10"/><path d="M30 28v10"/><path d="M14 34h16"/></svg>`,
  "6": `<svg viewBox="0 0 44 44" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"><circle cx="14" cy="20" r="6"/><circle cx="30" cy="20" r="6"/><path d="M22 8v28"/><path d="M20 10c-4 2-8 6-6 10"/><path d="M24 10c4 2 8 6 6 10"/></svg>`,
  "7": `<svg viewBox="0 0 44 44" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"><rect x="10" y="18" width="24" height="18" rx="2"/><path d="M16 18v-4a6 6 0 0112 0v4"/><circle cx="22" cy="28" r="3"/><path d="M22 31v3"/></svg>`,
  "8": `<svg viewBox="0 0 44 44" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"><path d="M22 6v32"/><path d="M10 20h24"/><circle cx="16" cy="14" r="4"/><circle cx="28" cy="14" r="4"/><path d="M14 32h16"/></svg>`,
  "9": `<svg viewBox="0 0 44 44" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"><circle cx="22" cy="12" r="4"/><path d="M22 16v16"/><path d="M14 38l8-6 8 6"/><path d="M16 24l6 4 6-4"/></svg>`,
  "10": `<svg viewBox="0 0 44 44" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"><circle cx="22" cy="22" r="14"/><circle cx="22" cy="22" r="6"/><path d="M22 8v4M22 32v4M8 22h4M32 22h4"/></svg>`,
  "11": `<svg viewBox="0 0 44 44" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"><path d="M10 22c4-8 20-8 24 0"/><path d="M10 22c4 8 20 8 24 0"/><circle cx="22" cy="22" r="4"/><path d="M18 14l4-6 4 6"/></svg>`,
  "12": `<svg viewBox="0 0 44 44" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"><path d="M22 10v24"/><path d="M14 18l8-8 8 8"/><circle cx="22" cy="32" r="4"/><path d="M16 10h12"/></svg>`,
  "13": `<svg viewBox="0 0 44 44" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"><path d="M8 36L22 8l14 28"/><path d="M14 28h16"/><circle cx="22" cy="20" r="3"/><path d="M19 36h6"/></svg>`,
  "14": `<svg viewBox="0 0 44 44" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"><path d="M14 14l14 16"/><path d="M30 14L16 30"/><circle cx="14" cy="22" r="6"/><circle cx="30" cy="22" r="6"/></svg>`,
  "15": `<svg viewBox="0 0 44 44" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"><circle cx="22" cy="16" r="6"/><path d="M10 38c0-8 5-14 12-14s12 6 12 14"/><path d="M18 10l-4-4M26 10l4-4M22 10v-4"/></svg>`,
  "16": `<svg viewBox="0 0 44 44" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"><rect x="14" y="6" width="16" height="24" rx="2"/><path d="M10 30l4 8h16l4-8"/><path d="M18 14h8M18 20h6"/></svg>`,
  "17": `<svg viewBox="0 0 44 44" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"><circle cx="22" cy="12" r="5"/><path d="M14 26c0-8 16-8 16 0"/><path d="M10 36c4-8 24-8 24 0"/><path d="M22 17v4"/></svg>`,
  "18": `<svg viewBox="0 0 44 44" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"><path d="M8 36c4-12 10-18 14-18s10 6 14 18"/><path d="M14 36c2-6 4-10 8-10s6 4 8 10"/><circle cx="22" cy="12" r="5"/></svg>`,
  "19": `<svg viewBox="0 0 44 44" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"><circle cx="22" cy="16" r="10"/><path d="M14 32l4-6h8l4 6"/><path d="M16 38h12"/><path d="M22 6v-2M30 9l2-2M36 16h2M30 23l2 2M14 9l-2-2M8 16h-2"/></svg>`,
  "20": `<svg viewBox="0 0 44 44" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"><path d="M22 6c6 0 14 4 14 10 0 8-6 12-14 12S8 24 8 16c0-6 8-10 14-10z"/><path d="M16 28l-4 10"/><path d="M28 28l4 10"/><path d="M16 38h12"/></svg>`,
  "21": `<svg viewBox="0 0 44 44" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"><ellipse cx="22" cy="22" rx="12" ry="16"/><path d="M14 10c-4-2-6 0-6 4"/><path d="M30 10c4-2 6 0 6 4"/><path d="M14 34c-4 2-6 0-6-4"/><path d="M30 34c4 2 6 0 6-4"/><circle cx="22" cy="22" r="3"/></svg>`
};

// ─── ARCANES (FR base) ───
const ARCANES = [
  { num: 0, roman: '0', name: 'Le Mat', altname: 'Le Fou / The Fool', keywords: ['Liberté', 'Aventure', 'Innocence', 'Nouveau départ'], upright: 'Début d\'un voyage, saut dans l\'inconnu. Liberté totale, insouciance créatrice, confiance en l\'univers.', reversed: 'Imprudence excessive, naïveté dangereuse ou fuite des responsabilités.', symbolism: 'Il marche au bord du précipice sans regarder en bas. L\'âme qui s\'engage sans le poids du passé.', domains: 'Nouveaux commencements, voyages imprévus, ruptures libératrices, créativité spontanée.' },
  { num: 1, roman: 'I', name: 'Le Bateleur', altname: 'Le Magicien / The Magician', keywords: ['Volonté', 'Habileté', 'Action', 'Initiative'], upright: 'Force de la volonté et habileté. Confiance en soi, initiative, transformation de l\'idée en acte.', reversed: 'Tromperie, manipulation, usage mal orienté des talents.', symbolism: 'Il lève une baguette vers le ciel. Canal entre l\'idée et la réalisation.', domains: 'Entrepreneuriat, communication, projets, habileté.' },
  { num: 2, roman: 'II', name: 'La Papesse', altname: 'La Grande Prêtresse / The High Priestess', keywords: ['Intuition', 'Mystère', 'Sagesse', 'Intériorité'], upright: 'Connaissance intérieure, intuition profonde. Invitation au silence et à l\'introspection.', reversed: 'Secrets nuisibles, intuition ignorée, refus d\'écouter sa voix intérieure.', symbolism: 'Gardienne du seuil entre le visible et l\'invisible, un livre ouvert sur les genoux.', domains: 'Vie intérieure, spiritualité, non-dits, études ésotériques.' },
  { num: 3, roman: 'III', name: "L'Impératrice", altname: 'La Reine / The Empress', keywords: ['Abondance', 'Fécondité', 'Création', 'Nature'], upright: 'Force créatrice par excellence. Fécondité, abondance, plaisirs des sens, maternité.', reversed: 'Stérilité, blocage créatif, dépendance affective, étouffement.', symbolism: 'Couronnée dans la nature florissante. Mère, reine et nature unie.', domains: 'Maternité, création artistique, abondance, corps.' },
  { num: 4, roman: 'IV', name: "L'Empereur", altname: 'Le Roi / The Emperor', keywords: ['Autorité', 'Structure', 'Stabilité', 'Pouvoir'], upright: 'Ordre établi, autorité bienveillante, structure solide. Capacité à gouverner et organiser.', reversed: 'Tyrannie, rigidité excessive, abus de pouvoir.', symbolism: 'Sur un trône de pierre — principe d\'ordre dans le monde manifesté.', domains: 'Carrière, leadership, père, droit, politique.' },
  { num: 5, roman: 'V', name: 'Le Pape', altname: 'Le Hiérophante / The Hierophant', keywords: ['Tradition', 'Enseignement', 'Guidance', 'Institution'], upright: 'Gardien des traditions, transmetteur du savoir. Le mentor, guide spirituel.', reversed: 'Dogmatisme, conformisme aveugle, manipulation spirituelle.', symbolism: 'Pont entre le divin et l\'humain, entre deux colonnes.', domains: 'Religion, institutions, enseignement, morale.' },
  { num: 6, roman: 'VI', name: "L'Amoureux", altname: 'Les Amants / The Lovers', keywords: ['Choix', 'Amour', 'Union', 'Désir'], upright: 'Choix crucial entre deux voies. Attraction, désir, nécessité de décider selon ses valeurs.', reversed: 'Hésitation, infidélité, mauvais choix, conflit de valeurs.', symbolism: 'Un homme entre deux femmes, un ange au-dessus. Archétype du carrefour existentiel.', domains: 'Relations amoureuses, décisions morales, partenariats.' },
  { num: 7, roman: 'VII', name: 'Le Chariot', altname: 'Le Char / The Chariot', keywords: ['Victoire', 'Maîtrise', 'Mouvement', 'Conquête'], upright: 'Victoire par la volonté et la maîtrise de soi. Conquête, mouvement en avant, succès mérité.', reversed: 'Perte de contrôle, arrogance, course sans direction.', symbolism: 'Un guerrier conduit un char tiré par deux sphinges opposées.', domains: 'Ambition, sport, transport, compétition.' },
  { num: 8, roman: 'VIII', name: 'La Justice', altname: 'La Balance / Justice', keywords: ['Équité', 'Vérité', 'Loi', 'Équilibre'], upright: 'Équité, vérité, conséquences de nos actes. Jugement juste, retour à l\'équilibre.', reversed: 'Injustice, biais, refus d\'assumer, déséquilibre.', symbolism: 'Tenant épée et balance sans passion. Loi impersonnelle — cause et effet.', domains: 'Légal, contrats, éthique, karma.' },
  { num: 9, roman: 'IX', name: "L'Hermite", altname: 'Le Sage / The Hermit', keywords: ['Solitude', 'Sagesse', 'Retraite', 'Recherche'], upright: 'Quête intérieure, retrait du monde. Il éclaire son propre chemin. Réflexion nécessaire.', reversed: 'Isolement stérile, refus du monde, immobilisme.', symbolism: 'Un vieillard avance seul avec une lanterne. La lumière est sa propre conscience.', domains: 'Retraite, méditation, études, recherche de sens.' },
  { num: 10, roman: 'X', name: 'La Roue de Fortune', altname: 'La Roue / Wheel of Fortune', keywords: ['Destin', 'Changement', 'Cycles', 'Chance'], upright: 'Tournant du destin, changement de cycle. Ce qui était bloqué se remet en mouvement.', reversed: 'Malchance conjoncturelle, résistance au changement, cycles négatifs.', symbolism: 'Roue cosmique — rien n\'est permanent.', domains: 'Chance, retournements, opportunités, karma.' },
  { num: 11, roman: 'XI', name: 'La Force', altname: 'Le Courage / Strength', keywords: ['Courage', 'Douceur', 'Endurance', 'Maîtrise'], upright: 'Courage intérieur, maîtrise des instincts par la douceur. Endurance, puissance tranquille.', reversed: 'Lâcheté, peur, brutalité, manque de confiance.', symbolism: 'Une femme ouvre sans violence la gueule d\'un lion.', domains: 'Santé, courage, gestion des émotions, animaux.' },
  { num: 12, roman: 'XII', name: 'Le Pendu', altname: "L'Homme Pendu / The Hanged Man", keywords: ['Suspension', 'Lâcher-prise', 'Sacrifice', 'Attente'], upright: 'Suspension volontaire, sacrifice consenti. Attente fertile, initiation par l\'inversion.', reversed: 'Refus de lâcher prise, martyre, résistance à la transformation.', symbolism: 'Suspendu par un pied, calme. L\'inversion révèle ce qui était caché.', domains: 'Transitions, crises initiatiques, deuils symboliques.' },
  { num: 13, roman: 'XIII', name: 'La Mort', altname: "L'Arcane sans nom / Death", keywords: ['Transformation', 'Fin de cycle', 'Renouveau', 'Passage'], upright: 'Fin d\'un cycle, transformation profonde et nécessaire. Ce qui doit mourir pour que naisse le nouveau.', reversed: 'Résistance à la transformation, stagnation, deuil mal traversé.', symbolism: 'Un squelette faucheur laisse derrière lui des pousses nouvelles.', domains: 'Fins, deuils, transformations radicales, ruptures.' },
  { num: 14, roman: 'XIV', name: 'La Tempérance', altname: "L'Ange / Temperance", keywords: ['Équilibre', 'Modération', 'Harmonie', 'Patience'], upright: 'Art de doser et mélanger les contraires. Harmonie retrouvée, guérison douce, alchimie intérieure.', reversed: 'Excès, impatience, déséquilibre, dissipation.', symbolism: 'Un ange transvase un liquide d\'une coupe à l\'autre.', domains: 'Santé, guérison, relations équilibrées, art.' },
  { num: 15, roman: 'XV', name: 'Le Diable', altname: 'Satan / The Devil', keywords: ['Attachement', 'Pulsion', 'Illusion', 'Matière'], upright: 'Les chaînes que l\'on se forge soi-même : addictions, obsessions, pulsions non maîtrisées.', reversed: 'Libération d\'une dépendance, prise de conscience.', symbolism: 'Deux personnages enchaînés — les chaînes sont lâches. L\'emprisonnement est consenti.', domains: 'Addictions, pulsions, pouvoir, argent, peurs.' },
  { num: 16, roman: 'XVI', name: 'La Maison-Dieu', altname: 'La Tour / The Tower', keywords: ['Rupture', 'Révélation', 'Choc', 'Effondrement'], upright: 'Rupture soudaine, effondrement de structures non saines. Crise libératrice, révélation fulgurante.', reversed: 'Catastrophe évitée, refus d\'accepter l\'inévitable.', symbolism: 'La foudre frappe une tour. La destruction précède une construction authentique.', domains: 'Crises, séparations soudaines, révélations, effondrements.' },
  { num: 17, roman: 'XVII', name: "L'Étoile", altname: "L'Espérance / The Star", keywords: ['Espoir', 'Inspiration', 'Guérison', 'Guidance'], upright: 'Espoir pur, guidance céleste, guérison après la tempête. Renouveau spirituel, foi en l\'avenir.', reversed: 'Désespoir, perte de foi, illusions déçues.', symbolism: 'Une femme verse l\'eau sous une grande étoile. Elle nourrit sans s\'épuiser.', domains: 'Guérison, art, rêves, vocation, spiritualité.' },
  { num: 18, roman: 'XVIII', name: 'La Lune', altname: 'Le Rêve / The Moon', keywords: ['Illusion', 'Rêve', 'Inconscient', 'Peur'], upright: 'Territoire des illusions et de l\'inconscient. Peurs nocturnes, révélations profondes.', reversed: 'Confusion dissipée ou plongée dans la paranoïa.', symbolism: 'La lune éclaire sans révéler — chemin sinueux entre deux tours.', domains: 'Inconscient, rêves, peurs, mensonges, cycles féminins.' },
  { num: 19, roman: 'XIX', name: 'Le Soleil', altname: 'La Clarté / The Sun', keywords: ['Joie', 'Succès', 'Clarté', 'Vitalité'], upright: 'Joie, succès, clarté d\'esprit, santé rayonnante, triomphe. Période lumineuse et épanouie.', reversed: 'Joie partielle, excès d\'ego, optimisme aveugle.', symbolism: 'Deux enfants dansent sous un soleil radieux. L\'innocence retrouvée.', domains: 'Santé, enfants, réussite, mariage, créativité.' },
  { num: 20, roman: 'XX', name: 'Le Jugement', altname: 'La Résurrection / Judgement', keywords: ['Appel', 'Réveil', 'Décision', 'Renaissance'], upright: 'Appel intérieur à se transformer. Réveil de la conscience, bilan de vie, renaissance.', reversed: 'Refus de l\'appel, culpabilité excessive, résurrection bloquée.', symbolism: 'Un ange sonne la trompette. Le réveil est collectif et individuel.', domains: 'Vocations, retour du passé, décisions définitives, prises de conscience.' },
  { num: 21, roman: 'XXI', name: 'Le Monde', altname: "L'Univers / The World", keywords: ['Accomplissement', 'Totalité', 'Succès', 'Intégration'], upright: 'Accomplissement total, synthèse réussie, réalisation de soi. Harmonie avec l\'univers.', reversed: 'Succès incomplet, voyage inachevé, dernier pas non franchi.', symbolism: 'Une figure androgyne danse dans une couronne de laurier. Le cosmos intégré.', domains: 'Voyage, diplôme, mariage, aboutissement, accomplissement.' }
];

// ─── ARCANES PT overrides ───
const ARCANES_PT = [
  { keywords: ['Liberdade', 'Aventura', 'Inocência', 'Novo começo'], upright: 'Início de uma jornada, salto para o desconhecido. Liberdade total, despreocupação criativa, confiança no universo.', reversed: 'Imprudência excessiva, ingenuidade perigosa ou fuga das responsabilidades.', symbolism: 'Caminha à beira do precipício sem olhar para baixo. A alma que avança sem o peso do passado.', domains: 'Novos começos, viagens imprevistas, rupturas libertadoras, criatividade espontânea.' },
  { keywords: ['Vontade', 'Habilidade', 'Acção', 'Iniciativa'], upright: 'Força da vontade e habilidade. Confiança em si, iniciativa, transformação da ideia em acto.', reversed: 'Engano, manipulação, uso mal orientado dos talentos.', symbolism: 'Levanta uma varinha em direcção ao céu. Canal entre a ideia e a realização.', domains: 'Empreendedorismo, comunicação, projectos, habilidade.' },
  { keywords: ['Intuição', 'Mistério', 'Sabedoria', 'Interioridade'], upright: 'Conhecimento interior, intuição profunda. Convite ao silêncio e à introspecção.', reversed: 'Segredos prejudiciais, intuição ignorada, recusa de escutar a voz interior.', symbolism: 'Guardiã do limiar entre o visível e o invisível, com um livro aberto no colo.', domains: 'Vida interior, espiritualidade, não-ditos, estudos esotéricos.' },
  { keywords: ['Abundância', 'Fertilidade', 'Criação', 'Natureza'], upright: 'Força criadora por excelência. Fertilidade, abundância, prazeres dos sentidos, maternidade.', reversed: 'Esterilidade, bloqueio criativo, dependência afectiva, sufocamento.', symbolism: 'Coroada na natureza florescente. Mãe, rainha e natureza unidas.', domains: 'Maternidade, criação artística, abundância, corpo.' },
  { keywords: ['Autoridade', 'Estrutura', 'Estabilidade', 'Poder'], upright: 'Ordem estabelecida, autoridade benevolente, estrutura sólida. Capacidade de governar e organizar.', reversed: 'Tirania, rigidez excessiva, abuso de poder.', symbolism: 'Num trono de pedra — princípio de ordem no mundo manifestado.', domains: 'Carreira, liderança, pai, direito, política.' },
  { keywords: ['Tradição', 'Ensino', 'Orientação', 'Instituição'], upright: 'Guardião das tradições, transmissor do saber. O mentor, guia espiritual.', reversed: 'Dogmatismo, conformismo cego, manipulação espiritual.', symbolism: 'Ponte entre o divino e o humano, entre duas colunas.', domains: 'Religião, instituições, ensino, moral.' },
  { keywords: ['Escolha', 'Amor', 'União', 'Desejo'], upright: 'Escolha crucial entre dois caminhos. Atracção, desejo, necessidade de decidir segundo os próprios valores.', reversed: 'Hesitação, infidelidade, má escolha, conflito de valores.', symbolism: 'Um homem entre duas mulheres, um anjo por cima. Arquétipo da encruzilhada existencial.', domains: 'Relações amorosas, decisões morais, parcerias.' },
  { keywords: ['Vitória', 'Mestria', 'Movimento', 'Conquista'], upright: 'Vitória pela vontade e domínio de si. Conquista, avanço, sucesso merecido.', reversed: 'Perda de controlo, arrogância, corrida sem direcção.', symbolism: 'Um guerreiro conduz um carro puxado por duas esfinges opostas.', domains: 'Ambição, desporto, transporte, competição.' },
  { keywords: ['Equidade', 'Verdade', 'Lei', 'Equilíbrio'], upright: 'Equidade, verdade, consequências dos nossos actos. Julgamento justo, retorno ao equilíbrio.', reversed: 'Injustiça, parcialidade, recusa de assumir, desequilíbrio.', symbolism: 'Segura espada e balança sem paixão. Lei impessoal — causa e efeito.', domains: 'Legal, contratos, ética, karma.' },
  { keywords: ['Solidão', 'Sabedoria', 'Recolha', 'Pesquisa'], upright: 'Demanda interior, retirada do mundo. Ilumina o próprio caminho. Reflexão necessária.', reversed: 'Isolamento estéril, recusa do mundo, imobilismo.', symbolism: 'Um ancião avança sozinho com uma lanterna. A luz é a sua própria consciência.', domains: 'Recolha, meditação, estudos, pesquisa de sentido.' },
  { keywords: ['Destino', 'Mudança', 'Ciclos', 'Sorte'], upright: 'Viragem do destino, mudança de ciclo. O que estava bloqueado recomeça a mover-se.', reversed: 'Azar conjuntural, resistência à mudança, ciclos negativos.', symbolism: 'Roda cósmica — nada é permanente.', domains: 'Sorte, reviravoltas, oportunidades, karma.' },
  { keywords: ['Coragem', 'Suavidade', 'Resistência', 'Mestria'], upright: 'Coragem interior, domínio dos instintos pela suavidade. Resistência, poder tranquilo.', reversed: 'Cobardia, medo, brutalidade, falta de confiança.', symbolism: 'Uma mulher abre sem violência a boca de um leão.', domains: 'Saúde, coragem, gestão das emoções, animais.' },
  { keywords: ['Suspensão', 'Desapego', 'Sacrifício', 'Espera'], upright: 'Suspensão voluntária, sacrifício consentido. Espera fértil, iniciação pela inversão.', reversed: 'Recusa de desapegar, martírio, resistência à transformação.', symbolism: 'Suspenso por um pé, calmo. A inversão revela o que estava oculto.', domains: 'Transições, crises iniciáticas, lutos simbólicos.' },
  { keywords: ['Transformação', 'Fim de ciclo', 'Renovação', 'Passagem'], upright: 'Fim de um ciclo, transformação profunda e necessária. O que deve morrer para que nasça o novo.', reversed: 'Resistência à transformação, estagnação, luto mal atravessado.', symbolism: 'Um esqueleto ceifador deixa atrás de si novos brotos.', domains: 'Fins, lutos, transformações radicais, rupturas.' },
  { keywords: ['Equilíbrio', 'Moderação', 'Harmonia', 'Paciência'], upright: 'Arte de dosar e misturar os contrários. Harmonia encontrada, cura suave, alquimia interior.', reversed: 'Excesso, impaciência, desequilíbrio, dissipação.', symbolism: 'Um anjo transvaza um líquido de um cálice para outro.', domains: 'Saúde, cura, relações equilibradas, arte.' },
  { keywords: ['Apego', 'Impulso', 'Ilusão', 'Matéria'], upright: 'As correntes que forjamos a nós próprios: vícios, obsessões, impulsos não dominados.', reversed: 'Libertação de uma dependência, tomada de consciência.', symbolism: 'Duas personagens acorrentadas — as correntes são folgadas. O aprisionamento é consentido.', domains: 'Vícios, impulsos, poder, dinheiro, medos.' },
  { keywords: ['Ruptura', 'Revelação', 'Choque', 'Colapso'], upright: 'Ruptura súbita, colapso de estruturas não saudáveis. Crise libertadora, revelação fulgurante.', reversed: 'Catástrofe evitada, recusa de aceitar o inevitável.', symbolism: 'O relâmpago atinge uma torre. A destruição precede uma construção autêntica.', domains: 'Crises, separações súbitas, revelações, colapsos.' },
  { keywords: ['Esperança', 'Inspiração', 'Cura', 'Orientação'], upright: 'Esperança pura, orientação celeste, cura após a tempestade. Renovação espiritual, fé no futuro.', reversed: 'Desespero, perda de fé, ilusões defraudadas.', symbolism: 'Uma mulher verte água sob uma grande estrela. Nutre sem se esgotar.', domains: 'Cura, arte, sonhos, vocação, espiritualidade.' },
  { keywords: ['Ilusão', 'Sonho', 'Inconsciente', 'Medo'], upright: 'Território das ilusões e do inconsciente. Medos nocturnos, revelações profundas.', reversed: 'Confusão dissipada ou mergulho na paranoia.', symbolism: 'A lua ilumina sem revelar — caminho sinuoso entre duas torres.', domains: 'Inconsciente, sonhos, medos, mentiras, ciclos femininos.' },
  { keywords: ['Clareza', 'Sucesso', 'Vitalidade', 'Alegria'], upright: 'Energia vital plena, sucesso claro, alegria autêntica. Clareza de mente, realização e celebração.', reversed: 'Sucesso adiado, egocentrismo, energia bloqueada.', symbolism: 'O sol brilha sobre dois gémeos dançando. Luz que não esconde nada.', domains: 'Saúde, sucesso, infância, clareza, casamento.' },
  { keywords: ['Julgamento', 'Chamamento', 'Renovação', 'Despertar'], upright: 'Chamamento interior irresistível. Despertar espiritual, segunda oportunidade, chamada da alma.', reversed: 'Auto-julgamento duro, recusa de despertar, culpa não resolvida.', symbolism: 'Um anjo toca a trombeta — os mortos ressuscitam para uma nova vida.', domains: 'Vocação, cura, segunda oportunidade, legado.' },
  { keywords: ['Realização', 'Totalidade', 'Sucesso', 'Integração'], upright: 'Realização total, síntese conseguida, realização de si. Harmonia com o universo.', reversed: 'Sucesso incompleto, viagem inacabada, último passo por dar.', symbolism: 'Uma figura andrógina dança numa coroa de louros. O cosmos integrado.', domains: 'Viagem, diploma, casamento, conclusão, realização.' }
];

// ─── SPREADS FR ───
const SPREADS_FR = [
  { id: 'ppf', name: 'Passé · Présent · Futur', count: 3, desc: 'Le tirage fondamental. Trajectoire temporelle d\'une situation.', positions: ['Le Passé — ce qui a mené ici', 'Le Présent — la situation actuelle', 'Le Futur — ce qui se profile'], layout: { type: 'grid', cols: 3, rows: 1, slots: [{ c: 1, r: 1 }, { c: 2, r: 1 }, { c: 3, r: 1 }] } },
  { id: 'oui-non', name: 'Oui / Non', count: 3, desc: 'Réponse directe à une question binaire.', positions: ['Ce qui favorise le Oui', 'La réponse centrale', 'Ce qui favorise le Non'], layout: { type: 'grid', cols: 3, rows: 1, slots: [{ c: 1, r: 1 }, { c: 2, r: 1 }, { c: 3, r: 1 }] } },
  { id: 'cae', name: 'Corps · Âme · Esprit', count: 3, desc: 'Regard holistique sur l\'état d\'un être.', positions: ['Le corps et l\'état physique', 'L\'âme et l\'état émotionnel', 'L\'esprit et l\'état mental'], layout: { type: 'vertical' } },
  { id: 'croix', name: 'Croix Celtique', count: 5, desc: 'Tirage approfondi sur une question centrale avec ses influences.', positions: ['La situation actuelle', 'Ce qui aide ou s\'oppose', 'Le dessous de la question', 'Le passé récent', 'Le futur proche'], layout: { type: 'grid', cols: 3, rows: 3, slots: [{ c: 2, r: 2 }, { c: 2, r: 1 }, { c: 2, r: 3 }, { c: 1, r: 2 }, { c: 3, r: 2 }] } },
  { id: 'amour', name: 'Tirage Amoureux', count: 5, desc: 'État des deux parties, obstacles, dynamique et potentiel d\'une relation.', positions: ['Vous dans la relation', 'L\'autre dans la relation', 'Le lien entre vous', 'Ce qui freine', 'Le potentiel de la relation'], layout: { type: 'amour' } },
  { id: 'vie', name: 'Chemin de Vie', count: 7, desc: 'Panorama complet : racines, présent, défis, ressources et destination.', positions: ['Les racines, le fondement', 'La situation présente', 'L\'obstacle principal', 'La ressource cachée', 'Ce qui vient du passé', 'L\'aide extérieure', 'L\'horizon'], layout: { type: 'grid', cols: 4, rows: 2, slots: [{ c: 1, r: 2 }, { c: 2, r: 1 }, { c: 3, r: 2 }, { c: 4, r: 1 }, { c: 1, r: 1 }, { c: 2, r: 2 }, { c: 4, r: 2 }] } },
  { id: 'fer', name: 'Fer à Cheval', count: 7, desc: 'Tirage classique en arc — passé, présent, avenir avec influences.', positions: ['Le passé lointain', 'Le passé récent', 'Le présent', 'Les obstacles futurs', 'Les personnes qui influencent', 'Ce qu\'il faut faire', 'Le résultat probable'], layout: { type: 'fer' } },
  { id: 'decision', name: 'À la Croisée des Chemins', count: 6, desc: 'Pour une décision entre deux options — chaque voie sur trois niveaux.', positions: ['Voie A — ce qui attire', 'Voie A — les obstacles', 'Voie A — l\'issue probable', 'Voie B — ce qui attire', 'Voie B — les obstacles', 'Voie B — l\'issue probable'], layout: { type: 'grid', cols: 2, rows: 3, slots: [{ c: 1, r: 1 }, { c: 1, r: 2 }, { c: 1, r: 3 }, { c: 2, r: 1 }, { c: 2, r: 2 }, { c: 2, r: 3 }] } }
];

// ─── SPREADS PT ───
const SPREADS_PT = [
  { id: 'ppf', name: 'Passado · Presente · Futuro', count: 3, desc: 'A tiragem fundamental. Trajectória temporal de uma situação.', positions: ['O Passado — o que levou até aqui', 'O Presente — a situação actual', 'O Futuro — o que se perfila'], layout: { type: 'grid', cols: 3, rows: 1, slots: [{ c: 1, r: 1 }, { c: 2, r: 1 }, { c: 3, r: 1 }] } },
  { id: 'oui-non', name: 'Sim / Não', count: 3, desc: 'Resposta directa a uma questão binária.', positions: ['O que favorece o Sim', 'A resposta central', 'O que favorece o Não'], layout: { type: 'grid', cols: 3, rows: 1, slots: [{ c: 1, r: 1 }, { c: 2, r: 1 }, { c: 3, r: 1 }] } },
  { id: 'cae', name: 'Corpo · Alma · Espírito', count: 3, desc: 'Visão holística do estado de um ser.', positions: ['O corpo e o estado físico', 'A alma e o estado emocional', 'O espírito e o estado mental'], layout: { type: 'vertical' } },
  { id: 'croix', name: 'Cruz Céltica', count: 5, desc: 'Tiragem aprofundada sobre uma questão central.', positions: ['A situação actual', 'O que ajuda ou se opõe', 'O fundo da questão', 'O passado recente', 'O futuro próximo'], layout: { type: 'grid', cols: 3, rows: 3, slots: [{ c: 2, r: 2 }, { c: 2, r: 1 }, { c: 2, r: 3 }, { c: 1, r: 2 }, { c: 3, r: 2 }] } },
  { id: 'amour', name: 'Tiragem Amorosa', count: 5, desc: 'Estado das duas partes, obstáculos e potencial de uma relação.', positions: ['Tu na relação', 'O outro na relação', 'O vínculo entre vós', 'O que trava', 'O potencial da relação'], layout: { type: 'amour' } },
  { id: 'vie', name: 'Caminho de Vida', count: 7, desc: 'Panorâmica completa: raízes, presente, desafios, recursos e destino.', positions: ['As raízes, o alicerce', 'A situação presente', 'O obstáculo principal', 'O recurso oculto', 'O que vem do passado', 'A ajuda exterior', 'O horizonte'], layout: { type: 'grid', cols: 4, rows: 2, slots: [{ c: 1, r: 2 }, { c: 2, r: 1 }, { c: 3, r: 2 }, { c: 4, r: 1 }, { c: 1, r: 1 }, { c: 2, r: 2 }, { c: 4, r: 2 }] } },
  { id: 'fer', name: 'Ferradura', count: 7, desc: 'Tiragem clássica em arco — passado, presente, futuro com influências.', positions: ['O passado distante', 'O passado recente', 'O presente', 'Os obstáculos futuros', 'As pessoas que influenciam', 'O que é preciso fazer', 'O resultado provável'], layout: { type: 'fer' } },
  { id: 'decision', name: 'Na Encruzilhada', count: 6, desc: 'Para uma decisão entre duas opções — cada via em três níveis.', positions: ['Via A — o que atrai', 'Via A — os obstáculos', 'Via A — o desfecho provável', 'Via B — o que atrai', 'Via B — os obstáculos', 'Via B — o desfecho provável'], layout: { type: 'grid', cols: 2, rows: 3, slots: [{ c: 1, r: 1 }, { c: 1, r: 2 }, { c: 1, r: 3 }, { c: 2, r: 1 }, { c: 2, r: 2 }, { c: 2, r: 3 }] } }
];

// ─── TRANSLATIONS ───
const L = {
  fr: {
    site_sub: 'Les Vingt-Deux Arcanes Majeurs',
    nav_accueil: 'Accueil',
    nav_tirage: 'Tirage',
    nav_arcanes: 'Arcanes',
    nav_moi: 'Moi',
    session_title: 'Nouvelle session',
    name_ph: 'Ton prénom',
    key_ph: 'Clé Groq — gsk_…',
    start_btn: 'Commencer la session →',
    session_note: 'Clé gratuite sur console.groq.com · Stockée localement.',
    end_btn: 'Terminer la session',
    err_name: 'Entre ton prénom',
    err_key: 'Clé trop courte',
    choose: 'Choisir un tirage',
    analyze: 'Analyser le tirage →',
    shuffle: 'Mélanger et tirer les cartes',
    shuffle_note: 'Ou cliquez sur chaque carte pour sélectionner manuellement selon votre tirage réel.',
    question_ph: 'Ex : Quelle direction prendre dans ma vie professionnelle ?',
    question_optional: '(facultatif)',
    back: '← Changer de tirage',
    new_spread: '← Nouveau tirage',
    pos_label: 'POSITION',
    click_pick: 'Cliquer pour choisir',
    rev_label: '↑ Renversée',
    turn_btn: 'Retourner',
    card_by_card: 'Carte par carte',
    global_r: 'Lecture globale',
    reading: 'Lecture',
    loading: 'Lecture en cours · · ·',
    deepen_title: 'Approfondir',
    deepen_desc: "Posez une question ou donnez du contexte — l'IA répond en tenant compte de vos cartes.",
    chat_ph: 'Ex: Cette lecture concerne ma situation professionnelle…',
    chat_send: 'Envoyer',
    lib_title: 'Les 22 Arcanes Majeurs',
    you: 'Vous',
    ai: 'IA',
    m_kws: 'Mots-clés',
    m_up: "Sens à l'endroit",
    m_rev: 'Sens renversé',
    m_sym: 'Symbolisme',
    m_dom: 'Domaines',
    quick_label: 'Tirage rapide',
    quick_shuffle_btn: 'Tirer & analyser en un clic →',
    quick_new: 'Nouveau tirage →',
    quick_desc: '3 cartes · Passé · Présent · Futur',
    prefs_title: 'Préférences',
    question_label: 'Ta question',
    session_end_label: 'SESSION',
    pref_fontsize: 'Taille du texte',
    pref_fontsize_normal: 'Normal',
    pref_fontsize_large: 'Grand',
    pref_fontsize_xlarge: 'Très grand',
    profil_title: 'Mon profil',
    profil_age: 'Âge',
    profil_situation: 'Situation amoureuse',
    profil_domaine: 'Domaine prioritaire en ce moment',
    profil_intention: 'Intention du moment',
    profil_note: "Ces informations enrichissent les lectures de l'IA. Elles restent sur cet appareil.",
    profil_intention_ph: 'Ce que tu traverses en ce moment, en quelques mots…',
    pref_theme: 'Thème',
    pref_lang: 'Langue',
    pref_theme_light: '☀ Clair',
    pref_theme_dark: '☾ Sombre',
    api_note: 'Clé gratuite sur <a href="https://console.groq.com/keys" target="_blank">console.groq.com</a> · Stockée localement sur cet appareil.',
    lang_menu_note: 'Pour le moment, seules ces deux langues sont disponibles.',
    btn_end: 'Terminer',
    btn_next: 'Suivant →',
    btn_start_tuto: 'Commencer',
    btn_skip: 'Passer',
    daily_label: 'Carte du jour',
    daily_reading_label: 'Lecture du jour',
    daily_reveal: 'Révéler la carte du jour',
    daily_see: "Voir l'arcane →",
    daily_next: h => `Nouvelle carte dans ${h}`,
    daily_locked_desc: h => `Votre carte quotidienne vous attend.<br>Elle changera dans ${h}.`,
    situation_opts: ['— Choisir —', 'Célibataire', 'En relation', 'Marié(e)', 'Séparé(e)', "C'est compliqué"],
    domaine_opts: ['— Choisir —', 'Amour & Relations', 'Travail & Carrière', 'Famille', 'Spiritualité', 'Santé', 'Finances', 'Développement personnel'],
    tuto: [
      { title: 'Accueil', desc: "Ta carte du jour t'attend chaque matin. Tire aussi 3 cartes en un clic." },
      { title: 'Tirages', desc: 'Choisis parmi 8 tirages. De 3 à 7 cartes selon ta question.' },
      { title: 'Arcanes', desc: 'Explore les 22 Arcanes Majeurs et leur symbolisme.' },
      { title: 'Moi', desc: 'Entre ta clé API et ton profil pour des lectures personnalisées.' },
    ],
    cards: n => `${n} carte${n > 1 ? 's' : ''}`,
    revs: n => `${n} renversée${n !== 1 ? 's' : ''}`,
    profil_ctx: (p) => {
      const parts = [];
      if (p.age) parts.push(`Âge : ${p.age} ans`);
      if (p.situation) parts.push(`Situation amoureuse : ${p.situation}`);
      if (p.domaine) parts.push(`Domaine prioritaire : ${p.domaine}`);
      if (p.intention) parts.push(`Contexte personnel : ${p.intention}`);
      return parts.length ? '\n\nContexte de la personne :\n' + parts.join('\n') : '';
    },
    daily_prompt: (a, reversed) => `Carte du jour : ${a.name} (Arcane ${a.roman})${reversed ? ' — RENVERSÉE' : ''}.\nMots-clés : ${a.keywords.join(', ')}.\nEn 2-3 phrases courtes et directes, dis ce que cette carte signifie pour aujourd'hui. Pas de titre, pas de "PARTIE", pas de structure. Juste le texte brut.`,
    suggestions_prompt: 'Génère exactement 3 questions très courtes (max 6 mots chacune) à la première personne (ex: "Comment améliorer ma situation ?") pour approfondir. Une par ligne, sans numéro, sans tiret.',
    sys: "Tu es un tarologue expert, direct et précis. Tu tutoies. Tes lectures sont concises : pas de remplissage, pas de formules vides. Pour les mots-clés essentiels mets les en valeurs en y ajoutant de la couleur <span style=\"color:#c97832;\">c97832</span>. Pour l'insight final ou invitation à l'action, commence par →. Respecte la structure PARTIE 1 / PARTIE 2.",
    prompt: (name, desc, lines, q) => 'Tirage : ' + name + (q ? '\nQuestion : ' + q : '') + '\n\nCartes :\n' + lines + '\n\nStructure ta réponse ainsi :\n\nPARTIE 1 — CARTE PAR CARTE\nPour chaque carte : 2-3 phrases. Rôle précis dans sa position. Commence par le Nom de la carte écrit en gras suivi d un tiret.\n\nPARTIE 2 — SYNTHÈSE\n3-4 phrases. Ce que le tirage dit dans son ensemble' + (q ? ' par rapport à la question posée' : '') + '. Termine par une invitation concrète introduite par →',
    spreads: SPREADS_FR,
  },
  pt: {
    site_sub: 'Os Vinte e Dois Arcanos Maiores',
    nav_accueil: 'Início',
    nav_tirage: 'Tiragem',
    nav_arcanes: 'Arcanos',
    nav_moi: 'Eu',
    session_title: 'Nova sessão',
    name_ph: 'O teu nome',
    key_ph: 'Chave Groq — gsk_…',
    start_btn: 'Iniciar sessão →',
    session_note: 'Chave gratuita em console.groq.com · Guardada localmente.',
    end_btn: 'Terminar sessão',
    err_name: 'Introduz o teu nome',
    err_key: 'Chave demasiado curta',
    choose: 'Escolher uma tiragem',
    analyze: 'Analisar a tiragem →',
    shuffle: 'Misturar e tirar as cartas',
    shuffle_note: 'Ou clique em cada carta para selecionar manualmente conforme o seu baralho real.',
    question_ph: 'Ex : Que caminho seguir na minha vida profissional ?',
    question_optional: '(facultativo)',
    back: '← Mudar de tiragem',
    new_spread: '← Nova tiragem',
    pos_label: 'POSIÇÃO',
    click_pick: 'Clica para escolher',
    rev_label: '↑ Invertida',
    turn_btn: 'Inverter',
    card_by_card: 'Carta a carta',
    global_r: 'Leitura global',
    reading: 'Leitura',
    loading: 'Leitura em curso · · ·',
    deepen_title: 'Aprofundar',
    deepen_desc: 'Faz uma pergunta ou dá contexto — a IA responde tendo em conta as tuas cartas.',
    chat_ph: 'Ex: Esta leitura diz respeito à minha situação profissional…',
    chat_send: 'Enviar',
    lib_title: 'Os 22 Arcanos Maiores',
    you: 'Tu',
    ai: 'IA',
    m_kws: 'Palavras-chave',
    m_up: 'Significado direito',
    m_rev: 'Significado invertido',
    m_sym: 'Simbolismo',
    m_dom: 'Domínios',
    quick_label: 'Tiragem rápida',
    quick_shuffle_btn: 'Tirar & analisar num clique →',
    quick_new: 'Nova tiragem →',
    quick_desc: '3 cartas · Passado · Presente · Futuro',
    prefs_title: 'Preferências',
    question_label: 'A tua questão',
    session_end_label: 'SESSÃO',
    pref_fontsize: 'Tamanho do texto',
    pref_fontsize_normal: 'Normal',
    pref_fontsize_large: 'Grande',
    pref_fontsize_xlarge: 'Muito grande',
    profil_title: 'O meu perfil',
    profil_age: 'Idade',
    profil_situation: 'Situação amorosa',
    profil_domaine: 'Domínio prioritário agora',
    profil_intention: 'Intenção do momento',
    profil_note: 'Estas informações enriquecem as leituras da IA. Ficam neste dispositivo.',
    profil_intention_ph: 'O que atravessas agora, em poucas palavras…',
    pref_theme: 'Tema',
    pref_lang: 'Língua',
    pref_theme_light: '☀ Claro',
    pref_theme_dark: '☾ Escuro',
    api_note: 'Chave gratuita em <a href="https://console.groq.com/keys" target="_blank">console.groq.com</a> · Guardada localmente neste dispositivo.',
    lang_menu_note: 'Por enquanto, apenas estas duas línguas estão disponíveis.',
    btn_end: 'Terminar',
    btn_next: 'Seguinte →',
    btn_start_tuto: 'Começar',
    btn_skip: 'Saltar',
    daily_label: 'Carta do dia',
    daily_reading_label: 'Leitura do dia',
    daily_reveal: 'Revelar a carta do dia',
    daily_see: 'Ver o arcano →',
    daily_next: h => `Nova carta dentro de ${h}`,
    daily_locked_desc: h => `A tua carta diária está à tua espera.<br>Mudará dentro de ${h}.`,
    situation_opts: ['— Escolher —', 'Solteiro(a)', 'Em relação', 'Casado(a)', 'Separado(a)', 'É complicado'],
    domaine_opts: ['— Escolher —', 'Amor & Relações', 'Trabalho & Carreira', 'Família', 'Espiritualidade', 'Saúde', 'Finanças', 'Desenvolvimento pessoal'],
    tuto: [
      { title: 'Início', desc: 'A tua carta do dia espera-te todas as manhãs. Tira também 3 cartas num clique.' },
      { title: 'Tiragens', desc: 'Escolhe entre 8 tiragens. De 3 a 7 cartas conforme a tua questão.' },
      { title: 'Arcanos', desc: 'Explora os 22 Arcanos Maiores e o seu simbolismo.' },
      { title: 'Eu', desc: 'Introduz a tua chave API e o teu perfil para leituras personalizadas.' },
    ],
    cards: n => `${n} carta${n > 1 ? 's' : ''}`,
    revs: n => `${n} invertida${n !== 1 ? 's' : ''}`,
    profil_ctx: (p) => {
      const parts = [];
      if (p.age) parts.push(`Idade : ${p.age} anos`);
      if (p.situation) parts.push(`Situação amorosa : ${p.situation}`);
      if (p.domaine) parts.push(`Domínio prioritário : ${p.domaine}`);
      if (p.intention) parts.push(`Contexto pessoal : ${p.intention}`);
      return parts.length ? '\n\nContexto da pessoa :\n' + parts.join('\n') : '';
    },
    daily_prompt: (a, reversed) => `Carta do dia: ${a.name} (Arcano ${a.roman})$ {reversed ? ' — REVERSO': ''}.\nPalavras-chave: ${a.keywords.join(',')}.\nEm 2-3 frases curtas e diretas, diga o que esta carta significa para hoje. Sem título, sem “PARTE”, sem estrutura. Apenas o texto bruto.`,
    suggestions_prompt: 'Gere exatamente 3 perguntas muito curtas (máximo de 6 palavras cada) na primeira pessoa (ex: "Como melhorar a minha situação?") para aprofundar. Uma por linha, sem número, sem travessão.',
    sys: "Você é um tarólogo experiente, direto e preciso. Você usa o 'tu'. As suas leituras são concisas: sem preenchimento, sem fórmulas vazias. Para as palavras-chave essenciais, destaque-as adicionando a cor <span style=\"color:#c97832;\">c97832</span>. Para a visão final ou convite à ação, comece com →. Respeite a estrutura PARTE 1 / PARTE 2.",
    prompt: (name, desc, lines, q) => 'Leitura: ' + name + (q ? '\nPergunta: ' + q : '') + '\n\nCartas:\n' + lines + '\n\nEstruture a sua resposta da seguinte forma:\n\nPARTE 1 — CARTA POR CARTA\nPara cada carta: 2-3 frases. Função precisa na sua posição. Comece com o nome da carta escrito em negrito seguido de um traço.\n\nPARTE 2 — SÍNTESE\n3-4 frases. O que a leitura diz no seu conjunto' + (q ? ' em relação à pergunta feita' : '') + '. Termine com um convite concreto introduzido por →',
    spreads: SPREADS_FR,
  },
};